### PR TITLE
Import Python changes from Geany + fixes and additional improvements

### PR DESCRIPTION
**Pull request by b4n**
Import Geany changes to the Python parser.  Also fix a bug in a Geany change, and further improve access reporting.

Fixes part of #216 (and various other bugs, see commits).

### CODE REVIEW

**Comment by b4n** [comment]
I have an additional commit that doesn't come from Geany but improves the access reporting further, and fixes #216: 22c4cbe47e4985aefede1dee9dbeca382ebd5105.  I'm not sure if I should add it here or PR it afterward (as it doesn't fit the title to the PR here).  Anyhow if this gets merged I can make another PR then :)

**Comment by fishman** [comment]
haven't checked the last two patches yet, but these patches don't really have anything to do with each others besides the fact that theyre from geany. therefore, personally, i don't think adding the patch from #216 is a problem. If the pull request title is a problem just change it or add the patches to the new one. I guess if this was a mailing list it would be a v2 patchset anyway, so I'm not sure what standard procedure we want to follow on github, yet.

**Comment by b4n** [comment]
> haven't checked the last two patches yet, but these patches don't really have anything to do with each others besides the fact that theyre from geany. therefore, personally, i don't think adding the patch from #216 is a problem.

OK, fair enough indeed.  So, I added it here.

**Comment by b4n** [comment]
You guys are OK with me (or anyone, really ^^) merging this?

**Comment by vhda** [comment]
Just one question: is it valid to have empty extended attributes (`file:` in this case)?

**Comment by b4n** [comment]
> Just one question: is it valid to have empty extended attributes (`file:` in this case)?

yes.  `file:` is generated by `entry->isFileScope` and means "this has file scope".  All parsers that set this field will generate an empty `file:` field (see for example `git grep -P '\tfile:' Units/`).

This said, and as mentioned in the commit https://github.com/b4n/fishman-ctags/commit/c16f0b819e1f2302e20f3d3f14d85af5bc6c9e1e#diff-e9dffeb0a60dddb2b51c1d8b6b15c3c9R198 I'm not certain setting `isFileScope` is useful/the thing to do.

**Comment by fishman** [comment]
merge is fine imho

**Pull request merged**
