### PR TITLE
Remove files related to unmaintained platforms

### PR DESCRIPTION
**Pull request by masatake**
Signed-off-by: Masatake YAMATO <yamato@redhat.com>

### CODE REVIEW

**Comment by ffes** [comment]
I think ``mac.c`` and ``qdos.c`` can be added to these files as well.

**Comment by ffes** [comment]
And ``win32\makefile.in`` and ``win32\ctags.ide``. All old Borland compiler related files AFAICS

**Comment by ffes** [comment]
And what about the references to these files in ``general.h`` and other files? Do ``grep -i amiga *.[ch]`` to see what I mean.

**Comment by masatake** [comment]
I rearranged the patches.
I should mention the dropped platfroms in docs/f-news.rst.
I will do it after #182 is merged.

**Comment by ffes** [comment]
I just tested your branch and everything still works fine with both MSVC and MinGW.

**Comment by masatake** [comment]
@ffes, thank you for testing.

**Pull request merged**
