### PR TITLE
make: Various fixes and improvements

### PR DESCRIPTION
**Pull request by b4n**
A follow up to #264 fixing all bugs I know in Make support, and adding a few features.  Fixes all our current tests, and adds a few.

### CODE REVIEW

**Comment by ffes** [comment]
FYI: All the tests pass on Windows as well

**Comment by masatake** [comment]
@b4n, I also looked at the code. Though vStringStripTrailing() rejects an empty string, findMakeTags()
accepts the empty string in newMacro:

  vStringTerminate (name);
  vStringStripTrailing (name);
  newMacro (name); <<<<

So I think we need something guard condition like
  
  if (!isEmpty) {
     newMacro(name);
 }

**Comment by b4n** [comment]
> I also looked at the code. Though vStringStripTrailing() rejects an empty string, findMakeTags()
accepts the empty string in newMacro:

Well, I deliberately didn't check for empty strings here because `makeSimpleTag()` does the check on its side so I figured there was no need to add special handling for the unlikely case of an empty defined name.

This said, `isSpecialTarget()` is slightly buggy on empty names too: it accesses the first byte without a check.  This is not really important because `vString`s always have a non-zero-length buffer, but it's not very clean.  I'll fix this part.

With these in mind, do you still think the `newMacro()` call should be guarded?  I don't mind much really.

**Comment by masatake** [comment]
Thank you. I'm wrong. No needs the guard.

**Comment by b4n** [comment]
Added 8a52d51b9174b00d5ecdb67b10913280309f77b8 to fix the small `isSpecialTarget()` issue, even though the bug cannot happen in practice, and even if it did it wouldn't have any impact.

**Comment by masatake** [comment]
@b4n, thank you. Both fuzz and noise targets are passed. It is ready to merge.

**Pull request merged**
