### PR TITLE
c: record the "#include" file as a kind 'I'

### PR DESCRIPTION
**Pull request by masatake**
NOTE: chars around included file (", <, and >) are recorded,
too.

Signed-off-by: Masatake YAMATO <yamato@redhat.com>

### CODE REVIEW

**Comment by ffes** [comment]
Great idea! LGTM.

At first I was not sure about the extra characters surrounding the filename, but giving it a second thought I think you are right. When you use those tags for building a tree or something like that it surely is useful information.

**Comment by vhda** [comment]
I only use tags inside vim and it already is able to identify included files by itself without searching for tags. Assuming that there are more people in the same situation as myself, I think that having this as an option would make more sense. Personally, I would have it disabled by default to keep it consistent with older versions, but as long as there is an option I'm OK with it.

**Comment by vhda** [comment]
Should have looked at the patch morecarefully before posting. My bad :)

**Comment by ffes** [comment]
@vhda This feature is an option and is disabled by default.

**Comment by ffes** [comment]
@vhda See your second comment appear when I submitted mine :-)

**Comment by vhda** [comment]
In my defense, I'm still in bed... :P

**Comment by ffes** [comment]
The Linux-clang job of Travis was having troubles to start. I had to restart it a couple of times but now it succeeded.

**Comment by masatake** [comment]
Thank you for comments.
Recording the information between files is new area for ctags.
I will write something interesting application when I cannot find anything more to work on ctags:-P.
Try adding the same kinds to your favourite languages.

**Comment by masatake** [comment]
TODO: Deal #import of objc.

**Pull request merged**
