### PR TITLE
D: Parse function & aggregate declaration templates

### PR DESCRIPTION
**Pull request by ntrel**
I.e. class, struct, interface, union.

### CODE REVIEW

**Comment by b4n** [comment]
So, LGTM

**Comment by masatake** [comment]
You removed TAG_FUNCTION_TEMPLATE. Is it really o.k.?
Don't you need a separate kind of function template?

**Comment by ntrel** [comment]
The code to parse DECL_FUNCTION_TEMPLATE was never enabled: https://github.com/fishman/ctags/pull/207/files#diff-9c07e5e602aac928d6d779592925a132L2504. So it's not really removing anything. In D there are function, class, struct, union, enum and alias template declarations, I really don't think it's worth having separate tag types for each of them.

**Comment by masatake** [comment]
I see. Thank you.

**Pull request merged**
