### PR TITLE
Fixed MSVC 2013 warnings, small changes in EXENDING.html

### PR DESCRIPTION
**Pull request by bmateusz**
Found some typo in the example code. I also added a hint for debugging,
I would found it useful.

### CODE REVIEW

**Comment by masatake** [comment]
Thank you for patches. However, could you splits this PR to smaller PRs for each issues?
So reviewing becomes easier. 
I would like to merge  14d218c and b85937e first. 1c3a41b deals many topics. I would like you to split 1c3a41b into smaller patch sets.

Thank you again.

**Comment by ffes** [comment]
Thanks for the patches! But it is not the preferred method to fix 3 completely unrelated problems with one PR. Could you please split them in three PRs, so we can review them separately?

**Comment by ffes** [comment]
I see @masatake already gave a similar answer ;-)

**Comment by bmateusz** [comment]
@masatake @ffes Ok I create separate PRs.

**Pull request closed without merging**
