### PR TITLE
Fix D access modifiers

### PR DESCRIPTION
**Pull request by jakeprobst**
So previously ctags would think D was C++ and look for `public:`.
That actually doesn't work in D.
D uses Java/C# style modifiers where each method/var has its own:
`private int a() { ... }`
It also does its own thing:
`private {
    void a() {
        ...
    }
    void b {
        ...
    }
}`

### CODE REVIEW

**Comment by vhda** [comment]
It would be nice if you could include a test unit to demonstrate the change you implemented and to avoid future regressions.

**Comment by masatake** [comment]
About the unit test see docs/units.rst.

**Comment by ntrel** [comment]
It's good you're working on this, but D does have `public:` - from http://dlang.org/attribute.html:

```
AttributeSpecifier:
    Attribute :
    Attribute DeclarationBlock

Attribute:
    ...
    ProtectionAttribute

ProtectionAttribute:
    private
    package
    package ( IdentifierList )
    protected
    public
    export
```
So please revert the `simple.d` changes.

**Comment by jakeprobst** [comment]
The documentation was unclear and I couldn't find any examples with the C++ style so I thought it wasn't supported.
It should support all methods of access declarations now.

**Comment by masatake** [comment]
Thank you for contributing.
fuzz target in Makefile says ctags with your patch crashes in following operation::
  
  [yamato@x201]~/var/ctags-github% cat /tmp/broken.d
  a::public
  [yamato@x201]~/var/ctags-github% ./ctags -o - /tmp/broken.d
  zsh: segmentation fault (core dumped)  ./ctags -o - /tmp/broken.d

**Comment by jakeprobst** [comment]
Ok, it it now passes all tests done by `make fuzz`

**Comment by masatake** [comment]
Thank you.

**Pull request merged**
