### PR TITLE
[wip] Travis fuzz

### PR DESCRIPTION
**Pull request by nenadalm**
shouldn't be merged yet since it passes even if the commands fails:
https://travis-ci.org/nenadalm/ctags/jobs/50103452

### CODE REVIEW

**Comment by b4n** [comment]
[Travis said](https://travis-ci.org/fishman/ctags/jobs/50104831#L1584):
> Your test run exceeded 50 minutes. 

I think we should not run inside Valgrind on Travis :)

**Comment by b4n** [comment]
…I really think that running inside Valgrind on Travis is a waste of time and resources compared to the gain.  Sure it'd be nice and all, but you get 16 builds of almost 50mins (if not more) -- the whole thing failed because 5 builds timed out (and one failed completely, independently of us) after 11h26mins worth of machine time.

On my machine, `make fuzz` takes about 2m (122s).  `make fuzz LANGUAGES=Ada` takes about 2s (1.95s).  `make fuzz LANGUAGES=Ada VG=1` takes… 8m31 (511s) -- basically 250 times slower.  So my question is, are the Valgrind runs on *each* push worth 250 times the resources needed without?

**Comment by nenadalm** [comment]
@b4n then feel free to close this PR

**Comment by nenadalm** [comment]
and these doesn't work: TEST_COMMAND="make fuzz VG=1 LANGUAGES=BETA,SLang" (just saying)

**Comment by b4n** [comment]
> and these doesn't work:
```$ make fuzz VG=1 LANGUAGES=BETA,SLang```
(just saying)

#239 fixes the BETA issue, thanks.
I can't reproduce the SLang one though, here `make fuzz LANGUAGES=SLang VG=1` works fine.

**Comment by masatake** [comment]
@nenadalm, valgrind log may be recorded somewhere under each test cases.
About SLang, if you have such log, could you open a new issue and paste the log to the issue?
(Or put the log on your gist, and tell us the url(?) for the gist via the issue?)

**Comment by nenadalm** [comment]
that's weird. on my local it works either. it seems it only doesn't work on travis: https://travis-ci.org/fishman/ctags/jobs/50308187

**Comment by nenadalm** [comment]
closing as this won't be probably merged

**Pull request closed without merging**
